version: 2
jobs:
  test:
    docker:
      - image: cimg/node:12
    steps:
      - checkout
      - restore_cache:
          key: node-modules-12-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-12-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: node-modules-lts-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-lts-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test
